# Generated by Django 5.2 on 2025-04-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_picture',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
