# Generated by Django 5.2 on 2025-04-13 09:09

import uuid
from django.db import migrations, models


def populate_uuid(apps, schema_editor):
    Message = apps.get_model('api', 'Message')
    for message in Message.objects.all():
        message.uuid = uuid.uuid4()
        message.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_profile_picture_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(populate_uuid),
        migrations.AlterField(
            model_name='message',
            name='uuid',
            field=models.UUIDField(unique=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
